name: lpcapital
description: Flutter project for the users of LPCapital

publish_to: 'none' 

version: 1.0.6+6

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_secure_storage: ^5.0.2
  rxdart: ^0.27.4
  pin_input_text_field: ^4.1.2
  dio: ^4.0.6
  equatable: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^7.3.3
  mask_text_input_formatter: ^2.3.0
  intl: ^0.17.0
  permission_handler: ^10.0.0
  fluttertoast: ^8.0.9
  package_info_plus: ^1.4.2
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^5.2.4
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.5.0
  firebase_crashlytics: ^2.8.5
  url_launcher: ^6.1.5
  dropdown_search: ^5.0.3
  flutter_masked_text2: ^0.9.1
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.0+1
  data_table_2: ^2.3.8
  flutter_countdown_timer: ^4.1.0
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_app_name:
  name: "LPCapital"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/ic_logo_2.png


flutter:
  uses-material-design: true
  assets:
    - assets/